services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: streamsense-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
      - --pandaproxy-addr
      - 0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - redpanda:8082
    ports:
      - "9092:9092"
      - "8082:8082"

  postgres:
    image: postgres:16
    container_name: streamsense-postgres
    environment:
      POSTGRES_USER: streamsense
      POSTGRES_PASSWORD: streamsense
      POSTGRES_DB: streamsense
    ports:
      - "5432:5432"
    volumes:
      - streamsense_pg:/var/lib/postgresql/data

  backend:
    build: ../backend
    container_name: streamsense-backend
    environment:
      DATABASE_URL: postgres://streamsense:streamsense@postgres:5432/streamsense
      KAFKA_BROKER: redpanda:9092
    depends_on:
      - postgres
      - redpanda
    ports:
      - "8000:8000"

  worker:
    build: ../worker
    container_name: streamsense-worker
    environment:
      DATABASE_URL: postgres://streamsense:streamsense@postgres:5432/streamsense
      KAFKA_BROKER: redpanda:9092
      TOPIC_EVENTS: events
    depends_on:
      - postgres
      - redpanda

volumes:
  streamsense_pg: